export type Lang = "en" | "vi"

export const LABELS: Record<Lang, Record<string, string>> = {
  en: {
    profile:         "Profile",
    profileSub:      "Manage your account settings",
    account:         "Account",
    displayName:     "Display Name",
    email:           "Email",
    memberSince:     "Member since",
    language:        "Language",
    languageSub:     "Choose your preferred language",
    english:         "English",
    vietnamese:      "Vietnamese",
    exportData:      "Export Data",
    exportSub:       "Download your transactions",
    exportCSV:       "Export as CSV",
    exportExcel:     "Export as Excel",
    exportCSVDesc:   "Comma-separated values, compatible with any spreadsheet app",
    exportExcelDesc: "Microsoft Excel format (.xlsx)",
    security:        "Security",
    securitySub:     "Update your password",
    currentPassword: "Current Password",
    newPassword:     "New Password",
    confirmPassword: "Confirm New Password",
    updatePassword:  "Update Password",
    cancel:          "Cancel",
    changePassword:  "Change Password",
    logout:          "Log out",
    save:            "Save Changes",
    namePlaceholder: "Your name",
    preparing:       "Preparing…",
  },
  vi: {
    profile:         "Hồ sơ",
    profileSub:      "Quản lý cài đặt tài khoản của bạn",
    account:         "Tài khoản",
    displayName:     "Tên hiển thị",
    email:           "Email",
    memberSince:     "Thành viên từ",
    language:        "Ngôn ngữ",
    languageSub:     "Chọn ngôn ngữ ưa thích",
    english:         "Tiếng Anh",
    vietnamese:      "Tiếng Việt",
    exportData:      "Xuất dữ liệu",
    exportSub:       "Tải xuống các giao dịch của bạn",
    exportCSV:       "Xuất CSV",
    exportExcel:     "Xuất Excel",
    exportCSVDesc:   "Định dạng CSV, tương thích với mọi ứng dụng bảng tính",
    exportExcelDesc: "Định dạng Microsoft Excel (.xlsx)",
    security:        "Bảo mật",
    securitySub:     "Cập nhật mật khẩu của bạn",
    currentPassword: "Mật khẩu hiện tại",
    newPassword:     "Mật khẩu mới",
    confirmPassword: "Xác nhận mật khẩu mới",
    updatePassword:  "Cập nhật mật khẩu",
    cancel:          "Hủy",
    changePassword:  "Đổi mật khẩu",
    logout:          "Đăng xuất",
    save:            "Lưu thay đổi",
    namePlaceholder: "Tên của bạn",
    preparing:       "Đang chuẩn bị…",
  },
}

export const fmtDate = (d: string | Date, lang: Lang) =>
  new Date(d).toLocaleDateString(lang === "vi" ? "vi-VN" : "en-US", {
    day: "numeric", month: "long", year: "numeric",
  })